### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by kalek3** [sulimanzeen/TS3_OnlineBot#1]
Hi, I know this is not the right place here, but I am desperate, and I urgently need to contact you. Please write me on TG (@kalek33), or give me your immediate writing contact. Thank you

**Comment by sulimanzeen** [comment]
Hi There,


Well, I am not available in TG. But you can join this TeamSpeak server "Synchrom.eu" and ask them about me using This Nickname: SulimanZeen












Kind Regards
SulimanZeen
